import React, { useState } from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import AboutMe from './aboutme';
import Experience from './experience'; // Example imports for other sections
import Projects from './projects';
import Skills from './skills';
import Hobbies from './hobbies';

const inter = Inter({ subsets: ['latin'] });

const sections = ['About', 'Experience', 'Projects', 'Skills', 'Contact'];

const Home = () => {
  const [selectedSection, setSelectedSection] = useState('About');

  const handleNavClick = (section) => {
    setSelectedSection(section);
  };

  const renderContent = () => {
    switch (selectedSection) {
      case 'About':
        return <AboutMe />;
      case 'Experience':
        return <Experience />;
      case 'Projects':
        return <Projects />;
      case 'Skills':
        return <Skills />;
      case 'Contact':
        return <Hobbies />;
      default:
        return <p>Welcome!</p>;
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <nav className={styles.nav}>
          {sections.map((section) => (
            <li key={section} className={styles.list}>
              <a href="#" onClick={() => handleNavClick(section)}>
                {section}
              </a>
            </li>
          ))}
        </nav>
        <div className={styles.container}>
          {renderContent()}
        </div>
      </main>
    </>
  );
};

export default Home;
